# Exploring the NYT Books API

## Importing packages and API key

In [1]:
# Importing important packages
from dotenv import load_dotenv
import os
import requests
import pandas as pd
from time import sleep
load_dotenv()

True

## Testing out the API call with the most recent bestsellers list

In [4]:
# This gets me the current list of fiction best sellers
url = f"https://api.nytimes.com/svc/books/v3/lists/current/combined-print-and-e-book-fiction.json?api-key={api_key}"
response = requests.get(url)

In [5]:
test = response.json()

In [6]:
test

{'status': 'OK',
 'copyright': 'Copyright (c) 2026 The New York Times Company. All Rights Reserved.',
 'num_results': 15,
 'last_modified': '2026-07-15T16:43:39Z',
 'results': {'display_name': 'Combined Print & E-Book Fiction',
  'list_name': 'Combined Print & E-Book Fiction',
  'list_name_encoded': 'combined-print-and-e-book-fiction',
  'previous_published_date': '2026-07-19',
  'published_date': '2026-07-26',
  'bestsellers_date': '2026-07-11',
  'normal_list_ends_at': 15,
  'updated': 'WEEKLY',
  'list_id': 704,
  'uri': 'nyt://bestsellerslist/de30e831-a20d-56d4-8f88-695162dc9183',
  'books': [{'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/1668236516?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Allen Levi',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9781668236512.jpg',
    'book_image_height': 0,
    'book_image_width': 0,
    'book_review_link': '',
    'book_uri': 'nyt://book/f3e1f4c8-34a3-54a3-8305-277666e21b4b',
    'contributor': 'by Allen Levi',
    'contributor_note': '',
    'created_date': '2026-03-04T23:40:20.88Z',
    'dagger': 0,
    'description': 'A man travels to a small Southern town, where he purchases pencil drawings of local residents and exchanges them for stories.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9781668236512',
    'publisher': 'Atria',
    'rank': 1,
    'rank_last_week': 1,
    'sunday_review_link': '',
    'title': 'THEO OF GOLDEN',
    'updated_date': '2026-03-04T23:40:20.88Z',
    'weeks_on_list': 32,
    'isbns': [{'isbn10': '', 'isbn13': '9781668236512'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/1668236516?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9781668236512?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9781668236512&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Ftheo-of-golden-allen-levi%2F1143923011%3Fean%3D9781668236512&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTheo-Golden%2FAllen-Levi%2F9781668236512'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9781668236512'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/059380421X?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Caro Claire Burke',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780593804216.jpg',
    'book_image_height': 400,
    'book_image_width': 312,
    'book_review_link': '',
    'book_uri': 'nyt://book/fb5cbc76-606c-50f7-b449-e958c73d2681',
    'contributor': 'by Caro Claire Burke',
    'contributor_note': '',
    'created_date': '2026-04-16T20:39:40.59Z',
    'dagger': 0,
    'description': 'Natalie Heller Mills, a privileged tradwife social media influencer, wakes up to find she is living in the comparatively difficult reality of 1855.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780593804216',
    'publisher': 'Knopf',
    'rank': 2,
    'rank_last_week': 2,
    'sunday_review_link': '',
    'title': 'YESTERYEAR',
    'updated_date': '2026-04-16T20:39:40.59Z',
    'weeks_on_list': 14,
    'isbns': [{'isbn10': '', 'isbn13': '9780593804216'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/059380421X?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780593804216?at=10lIEQ'},
     {'name': 'Barnes and Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780593804216&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fyesteryear-caro-claire-burke%2F1147793810%3Fean%3D9780593804216&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FYesteryear%2FCaro-Claire-Burke%2F9780593804216'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780593804216'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/B0DZJ53SVW?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Kathryn Stockett',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9781954118829.jpg',
    'book_image_height': 500,
    'book_image_width': 332,
    'book_review_link': '',
    'book_uri': 'nyt://book/6883473d-3592-5059-9606-49882d21d79d',
    'contributor': 'by Kathryn Stockett',
    'contributor_note': '',
    'created_date': '2026-07-15T16:43:32.494Z',
    'dagger': 0,
    'description': 'As things get tougher during the Depression, several women look for ways to improve their circumstances.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9781954118829',
    'publisher': 'Spiegel & Grau',
    'rank': 3,
    'rank_last_week': 3,
    'sunday_review_link': '',
    'title': 'THE CALAMITY CLUB',
    'updated_date': '2026-07-15T16:43:32.494Z',
    'weeks_on_list': 10,
    'isbns': [{'isbn10': '', 'isbn13': '9781954118829'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/B0DZJ53SVW?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9781954118829?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9781420531428&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-calamity-club-kathryn-stockett%2F1147098401%3Fean%3D9781420531428&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FCalamity-Club%2FKathryn-Stockett%2F9781954118812'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9781954118829'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/0593135202?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Andy Weir',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780593135228.jpg',
    'book_image_height': 400,
    'book_image_width': 312,
    'book_review_link': '',
    'book_uri': 'nyt://book/c11ceffc-2fff-5cb0-98c7-c4a75b2d16bd',
    'contributor': 'by Andy Weir',
    'contributor_note': '',
    'created_date': '2026-05-20T22:02:25.385Z',
    'dagger': 0,
    'description': 'Ryland Grace awakes from a long sleep alone and far from home, and the fate of humanity rests on his shoulders; the basis of the movie.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780593135228',
    'publisher': 'Ballantine',
    'rank': 4,
    'rank_last_week': 6,
    'sunday_review_link': '',
    'title': 'PROJECT HAIL MARY',
    'updated_date': '2026-05-20T22:02:25.385Z',
    'weeks_on_list': 57,
    'isbns': [{'isbn10': '', 'isbn13': '9780593135228'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/0593135202?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780593135211?at=10lIEQ'},
     {'name': 'Barnes and Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780593135228&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fproject-hail-mary-andy-weir%2F1137456421%3Fean%3D9780593135228&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FPROJECT%2BHAIL%2BMARY%2FAndy%2BWeir%2F9780593135228'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780593135228'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/0063511630?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Ann Patchett',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780063511637.jpg',
    'book_image_height': 400,
    'book_image_width': 312,
    'book_review_link': '',
    'book_uri': 'nyt://book/6480f0ac-57e1-5272-9566-118c913fe058',
    'contributor': 'by Ann Patchett',
    'contributor_note': '',
    'created_date': '2026-06-10T21:51:30.058Z',
    'dagger': 0,
    'description': 'Decades after their time together, a woman reconnects with her stepfather and they look back at the directions their lives have taken.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780063511637',
    'publisher': 'Harper',
    'rank': 5,
    'rank_last_week': 4,
    'sunday_review_link': '',
    'title': 'WHISTLER',
    'updated_date': '2026-06-10T21:51:30.058Z',
    'weeks_on_list': 6,
    'isbns': [{'isbn10': '', 'isbn13': '9780063511637'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/0063511630?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780063511637?at=10lIEQ'},
     {'name': 'Barnes and Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780063511637&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fwhistler-ann-patchett%2F1148504538%3Fean%3D9780063511637&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FWhistler%2FAnn-Patchett%2F9780063511637'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780063511637'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/0593820258?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Matt Dinniman',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780593820254.jpg',
    'book_image_height': 400,
    'book_image_width': 312,
    'book_review_link': '',
    'book_uri': 'nyt://book/e3ca1e41-0c69-5bc3-9f5c-e4668af53e44',
    'contributor': 'by Matt Dinniman',
    'contributor_note': '',
    'created_date': '2026-07-01T20:55:08.886Z',
    'dagger': 0,
    'description': 'A Coast Guard vet named Carl and his ex-girlfriend’s cat, Princess Donut, are trapped in a fantasy dungeon.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780593820254',
    'publisher': 'Ace',
    'rank': 6,
    'rank_last_week': 5,
    'sunday_review_link': '',
    'title': 'DUNGEON CRAWLER CARL',
    'updated_date': '2026-07-01T20:55:08.886Z',
    'weeks_on_list': 27,
    'isbns': [{'isbn10': '', 'isbn13': '9780593820254'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/0593820258?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9798688591507?at=10lIEQ'},
     {'name': 'Barnes and Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780593820254&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fdungeon-crawler-carl-matt-dinniman%2F1145437169%3Fean%3D9780593820254&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FDungeon-Crawler-Carl%2FMatt-Dinniman%2F9780593820254'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780593820254'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/0593600320?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Emily Giffin',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780593600320.jpg',
    'book_image_height': 500,
    'book_image_width': 329,
    'book_review_link': '',
    'book_uri': 'nyt://book/04ecd139-b764-54a9-8753-b6fe7d9332bb',
    'contributor': 'by Emily Giffin',
    'contributor_note': '',
    'created_date': '2026-07-15T16:43:32.638Z',
    'dagger': 0,
    'description': 'Shortly after becoming engaged, Billie receives a call from her first love that compels her to return to Wisconsin.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780593600320',
    'publisher': 'Ballantine',
    'rank': 7,
    'rank_last_week': 0,
    'sunday_review_link': '',
    'title': 'LOVE YOU MORE',
    'updated_date': '2026-07-15T16:43:32.638Z',
    'weeks_on_list': 1,
    'isbns': [{'isbn10': '', 'isbn13': '9780593600320'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/0593600320?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780593600320?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780593600320&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Flove-you-more-emily-giffin%2F1148477297%3Fean%3D9780593600320&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FLove-More%2FEmily-Giffin%2F9780593600320'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780593600320'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/0593819489?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Brigitte Knightley',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780593819487.jpg',
    'book_image_height': 500,
    'book_image_width': 331,
    'book_review_link': '',
    'book_uri': 'nyt://book/763a9cb8-1bf2-5295-8bdb-a1635acbfaed',
    'contributor': 'by Brigitte Knightley',
    'contributor_note': '',
    'created_date': '2026-07-15T16:43:32.778Z',
    'dagger': 0,
    'description': 'The second book in the Dearly Beloathed series. Boundaries weaken between an assassin and a healer.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780593819487',
    'publisher': 'Ace',
    'rank': 8,
    'rank_last_week': 0,
    'sunday_review_link': '',
    'title': 'THE EXQUISITE TORMENT OF LOVING YOUR ENEMY',
    'updated_date': '2026-07-15T16:43:32.778Z',
    'weeks_on_list': 1,
    'isbns': [{'isbn10': '', 'isbn13': '9780593819487'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/0593819489?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780593819487?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780593819487&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-exquisite-torment-of-loving-your-enemy-brigitte-knightley%2F1148477233%3Fean%3D9780593819487&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FExquisite-Torment-Loving-Your-Enemy%2FBrigitte-Knightley%2F9780593819487'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780593819487'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/0593798430?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Virginia Evans',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780593798430.jpg',
    'book_image_height': 400,
    'book_image_width': 312,
    'book_review_link': '',
    'book_uri': 'nyt://book/ee6e7478-d847-5258-a579-f9ef0ed9c301',
    'contributor': 'by Virginia Evans',
    'contributor_note': '',
    'created_date': '2026-04-29T21:22:33.974Z',
    'dagger': 0,
    'description': 'Letters from someone she used to know push Sybil Van Antwerp toward revisiting her past and finding a way to forgive.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780593798430',
    'publisher': 'Crown',
    'rank': 9,
    'rank_last_week': 11,
    'sunday_review_link': '',
    'title': 'THE CORRESPONDENT',
    'updated_date': '2026-04-29T21:22:33.974Z',
    'weeks_on_list': 35,
    'isbns': [{'isbn10': '', 'isbn13': '9780593798430'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/0593798430?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780593798430?at=10lIEQ'},
     {'name': 'Barnes and Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780593798430&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-correspondent-virginia-evans%2F1146138272%3Fean%3D9780593798430&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FCorrespondent%2FVirginia-Evans%2F9780593798430'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780593798430'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/1775293939?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Elle Kennedy',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9781775293934.jpg',
    'book_image_height': 500,
    'book_image_width': 333,
    'book_review_link': '',
    'book_uri': 'nyt://book/ead15738-5b14-5e39-b2fa-30efd062a916',
    'contributor': 'by Elle Kennedy',
    'contributor_note': '',
    'created_date': '2026-05-20T18:34:35.241Z',
    'dagger': 0,
    'description': 'Hannah Wells makes a deal with the captain of the college hockey team in exchange for tutoring him that may complicate their relationship.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9781775293934',
    'publisher': 'Bloom',
    'rank': 10,
    'rank_last_week': 7,
    'sunday_review_link': '',
    'title': 'THE DEAL',
    'updated_date': '2026-05-20T18:34:35.241Z',
    'weeks_on_list': 9,
    'isbns': [{'isbn10': '', 'isbn13': '9781775293934'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'https://www.amazon.com/dp/1775293939?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9781775293934?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9781775293934&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-deal-elle-kennedy%2F1121202984%3Fean%3D9781775293934&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FDeal%2FElle-Kennedy%2F9781775293934'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9781775293934'}]},
   {'age_group': '',
    'amazon_product_url': 'https://www.amazon.com/dp/1464249636?tag=thenewyorktim-20&linkCode=osi&th=1&psc=1',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Freida McFadden',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9781464249631.jpg',
    'book_image_height': 400,
    'book_image_width': 312,
    'book_review_link': '',
    'book_uri': 'nyt://book/bafd4a0f-0a01-56eb-b3b6-6d5d85d44ed3',
    'contributor': 'by Freida McFadden',
    'contributor_note': '',
    'created_date': '2026-06-03T18:55:48.983Z',
    'dagger': 0,
    'description': 'After her husband ends their marriage and she turns her attention to his new girlfriend, Naomi suspects she might be in danger.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9781464249631',
    'publisher': 'Poisoned Pen',
    'rank': 11,
    'rank_last_week': 10,
    'sunday_review_link': '',
    'title': 'THE DIVORCE',
    'updated_date': '2026-06-03T18:55:48.983Z',
    'weeks_on_list': 7,

The call returns 15 lists of books.

In [18]:
len(test["results"]["books"])

15

The description has one sentence that usually mentions the protagonist, so I plan to use this.

In [21]:
test["results"]["books"][0]["description"]

'A man travels to a small Southern town, where he purchases pencil drawings of local residents and exchanges them for stories.'

In [28]:
df = pd.json_normalize(test["results"]["books"])

In [33]:
df["description"]

0     A man travels to a small Southern town, where ...
1     Natalie Heller Mills, a privileged tradwife so...
2     Decades after their time together, a woman rec...
3     Ryland Grace awakes from a long sleep alone an...
4     The 25th book in the Scot Harvath series. Amer...
5     Hannah Wells makes a deal with the captain of ...
6     As things get tougher during the Depression, s...
7     A Coast Guard vet named Carl and his ex-girlfr...
8     After her husband ends their marriage and she ...
9     The second book in the Off-Campus series. A co...
10    The third book in the Off-Campus series. A bro...
11    Letters from someone she used to know push Syb...
12    A widow working the night shift at the Sowell ...
13    Sophie Drear is hired to revitalize a manor in...
14    After her fiancé leaves her, Frankie goes on h...
Name: description, dtype: str

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age_group             15 non-null     str
 1   amazon_product_url    15 non-null     str
 2   article_chapter_link  15 non-null     str
 3   asterisk              15 non-null     int64
 4   author                15 non-null     str
 5   book_image            15 non-null     str
 6   book_image_height     15 non-null     int64
 7   book_image_width      15 non-null     int64
 8   book_review_link      15 non-null     str
 9   book_uri              15 non-null     str
 10  contributor           15 non-null     str
 11  contributor_note      15 non-null     str
 12  created_date          15 non-null     str
 13  dagger                15 non-null     int64
 14  description           15 non-null     str
 15  first_chapter_link    15 non-null     str
 16  price                 15 non-null     str
 17  primary_isbn10        15 non-null     str
 18  primary_isbn13        15 non-null     str
 19  publisher             15 non-null     str
 20  rank                  15 non-null     int64
 21  rank_last_week        15 non-null     int64
 22  sunday_review_link    15 non-null     str
 23  title                 15 non-null     str
 24  updated_date          15 non-null     str
 25  weeks_on_list         15 non-null     int64
 26  isbns                 15 non-null     object
 27  buy_links             15 non-null     object
dtypes: int64(7), object(2), str(19)
memory usage: 3.4+ KB

## Getting the data from the NYT API

In [29]:
# Setting a variable to make sure the loop doesn't use all my API calls 
number_of_calls = 300

# Setting up an empty url variable for my calls
url = ""

# Setting up an empty variable for the date of the previous list
previous_published_date = ""

for i in range(number_of_calls):
    
    # if it is the first call, use the specific request for the current list so that we can get the dates
    if i == 0:
        url = f"https://api.nytimes.com/svc/books/v3/lists/current/combined-print-and-e-book-fiction.json?api-key={api_key}"
        response = requests.get(url)
        bestseller_list = response.json()

        # getting the date info I need for the next call
        previous_published_date = bestseller_list["results"]["previous_published_date"]
        # print(previous_published_date)
        
        # Getting the dataset I need
        bestselling_books = bestseller_list["results"]["books"]
        # print(bestselling_books[0])

        # Create a dataframe with the list of books
        bestselling_books_df = pd.json_normalize(bestselling_books)

        # Adding the additional columns with dates that I need
        published_date = bestseller_list["results"]["published_date"]
        bestselling_books_df["published_date"] = published_date

        bestsellers_date = bestseller_list["results"]["bestsellers_date"]
        bestselling_books_df["bestsellers_date"] = bestsellers_date

        # Since this will run a while, I am going to print to let myself know it worked
        print("Call 1 done")

        # Adding 12 seconds of sleep so as to not exceed the NYT call limit
        sleep(12)
        
    # For the answer other than the first call, use the date previous_published_date to call the previous list
    else: 
        url = f"https://api.nytimes.com/svc/books/v3/lists/{previous_published_date}/combined-print-and-e-book-fiction.json?api-key={api_key}"
        response = requests.get(url)
        bestseller_list = response.json()

        # getting the date info I need
        previous_published_date = bestseller_list["results"]["previous_published_date"]
        # print(previous_published_date)

        # Printing the info I need to check this worked
        bestselling_books = bestseller_list["results"]["books"]
        # print(bestselling_books[0])

        # Creating a new dataframe with the new list 
        new_bestselling_books_df = pd.json_normalize(bestselling_books)

        published_date = bestseller_list["results"]["published_date"]
        new_bestselling_books_df["published_date"] = published_date

        bestsellers_date = bestseller_list["results"]["bestsellers_date"]
        new_bestselling_books_df["bestsellers_date"] = bestsellers_date

        # Appending the new dataframe to the master data frame
        bestselling_books_df = pd.concat([bestselling_books_df, new_bestselling_books_df])

        # Since this will run a while, I am going to print to let myself know it worked
        print(f"Call {i} done")

        # Adding 12 seconds of sleep so as to not exceed the NYT call limit
        sleep(12)

Call 1 done
Call 1 done
Call 2 done
Call 3 done
Call 4 done
Call 5 done
Call 6 done
Call 7 done
Call 8 done
Call 9 done
Call 10 done
Call 11 done
Call 12 done
Call 13 done
Call 14 done
Call 15 done
Call 16 done
Call 17 done
Call 18 done
Call 19 done
Call 20 done
Call 21 done
Call 22 done
Call 23 done
Call 24 done
Call 25 done
Call 26 done
Call 27 done
Call 28 done
Call 29 done
Call 30 done
Call 31 done
Call 32 done
Call 33 done
Call 34 done
Call 35 done
Call 36 done
Call 37 done
Call 38 done
Call 39 done
Call 40 done
Call 41 done
Call 42 done
Call 43 done
Call 44 done
Call 45 done
Call 46 done
Call 47 done
Call 48 done
Call 49 done
Call 50 done
Call 51 done
Call 52 done
Call 53 done
Call 54 done
Call 55 done
Call 56 done
Call 57 done
Call 58 done
Call 59 done
Call 60 done
Call 61 done
Call 62 done
Call 63 done
Call 64 done
Call 65 done
Call 66 done
Call 67 done
Call 68 done
Call 69 done
Call 70 done
Call 71 done
Call 72 done
Call 73 done
Call 74 done
Call 75 done
Call 76 done
Call 77 done
Call 78 done
Call 79 done
Call 80 done
Call 81 done
Call 82 done
Call 83 done
Call 84 done
Call 85 done
Call 86 done
Call 87 done
Call 88 done
Call 89 done
Call 90 done
Call 91 done
Call 92 done
Call 93 done
Call 94 done
Call 95 done
Call 96 done
Call 97 done
Call 98 done
Call 99 done
Call 100 done
Call 101 done
Call 102 done
Call 103 done
Call 104 done
Call 105 done
Call 106 done
Call 107 done
Call 108 done
Call 109 done
Call 110 done
Call 111 done
Call 112 done
Call 113 done
Call 114 done
Call 115 done
Call 116 done
Call 117 done
Call 118 done
Call 119 done
Call 120 done
Call 121 done
Call 122 done
Call 123 done
Call 124 done
Call 125 done
Call 126 done
Call 127 done
Call 128 done
Call 129 done
Call 130 done
Call 131 done
Call 132 done
Call 133 done
Call 134 done
Call 135 done
Call 136 done
Call 137 done
Call 138 done
Call 139 done
Call 140 done
Call 141 done
Call 142 done
Call 143 done
Call 144 done
Call 145 done
Call 146 done
Call 147 done
Call 148 done
Call 149 done
Call 150 done
Call 151 done
Call 152 done
Call 153 done
Call 154 done
Call 155 done
Call 156 done
Call 157 done
Call 158 done
Call 159 done
Call 160 done
Call 161 done
Call 162 done
Call 163 done
Call 164 done
Call 165 done
Call 166 done
Call 167 done
Call 168 done
Call 169 done
Call 170 done
Call 171 done
Call 172 done
Call 173 done
Call 174 done
Call 175 done
Call 176 done
Call 177 done
Call 178 done
Call 179 done
Call 180 done
Call 181 done
Call 182 done
Call 183 done
Call 184 done
Call 185 done
Call 186 done
Call 187 done
Call 188 done
Call 189 done
Call 190 done
Call 191 done
Call 192 done
Call 193 done
Call 194 done
Call 195 done
Call 196 done
Call 197 done
Call 198 done
Call 199 done
Call 200 done
Call 201 done
Call 202 done
Call 203 done
Call 204 done
Call 205 done
Call 206 done
Call 207 done
Call 208 done
Call 209 done
Call 210 done
Call 211 done
Call 212 done
Call 213 done
Call 214 done
Call 215 done
Call 216 done
Call 217 done
Call 218 done
Call 219 done
Call 220 done
Call 221 done
Call 222 done
Call 223 done
Call 224 done
Call 225 done
Call 226 done
Call 227 done
Call 228 done
Call 229 done
Call 230 done
Call 231 done
Call 232 done
Call 233 done
Call 234 done
Call 235 done
Call 236 done
Call 237 done
Call 238 done
Call 239 done
Call 240 done
Call 241 done
Call 242 done
Call 243 done
Call 244 done
Call 245 done
Call 246 done
Call 247 done
Call 248 done
Call 249 done
Call 250 done
Call 251 done
Call 252 done
Call 253 done
Call 254 done
Call 255 done
Call 256 done
Call 257 done
Call 258 done
Call 259 done
Call 260 done
Call 261 done
Call 262 done
Call 263 done
Call 264 done
Call 265 done
Call 266 done
Call 267 done
Call 268 done
Call 269 done
Call 270 done
Call 271 done
Call 272 done
Call 273 done
Call 274 done
Call 275 done
Call 276 done
Call 277 done
Call 278 done
Call 279 done
Call 280 done
Call 281 done
Call 282 done
Call 283 done
Call 284 done
Call 285 done
Call 286 done
Call 287 done
Call 288 done
Call 289 done
Call 290 done
Call 291 done
Call 292 done
Call 293 done
Call 294 done
Call 295 done
Call 296 done
Call 297 done
Call 298 done
Call 299 done

Checking that it worked

In [30]:
 bestselling_books_df.shape

(4500, 30)

In [34]:
bestselling_books_df.head()

,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,book_uri,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
0,,https://www.amazon.com/dp/1668236516?tag=thene...,,0,Allen Levi,https://static01.nyt.com/bestsellers/images/97...,0,0,,nyt://book/f3e1f4c8-34a3-54a3-8305-277666e21b4b,...,1,1,,THEO OF GOLDEN,2026-03-04T23:40:20.88Z,30,"[{'isbn10': '', 'isbn13': '9781668236512'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
1,,https://www.amazon.com/dp/059380421X?tag=thene...,,0,Caro Claire Burke,https://static01.nyt.com/bestsellers/images/97...,400,312,,nyt://book/fb5cbc76-606c-50f7-b449-e958c73d2681,...,2,2,,YESTERYEAR,2026-04-16T20:39:40.59Z,12,"[{'isbn10': '', 'isbn13': '9780593804216'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
2,,https://www.amazon.com/dp/0063511630?tag=thene...,,0,Ann Patchett,https://static01.nyt.com/bestsellers/images/97...,400,312,,nyt://book/6480f0ac-57e1-5272-9566-118c913fe058,...,3,3,,WHISTLER,2026-06-10T21:51:30.058Z,4,"[{'isbn10': '', 'isbn13': '9780063511637'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
3,,https://www.amazon.com/dp/1954118813?tag=thene...,,0,Kathryn Stockett,https://static01.nyt.com/bestsellers/images/97...,400,312,,nyt://book/37a1d1e0-131c-5003-8a26-827e5b166569,...,4,7,,THE CALAMITY CLUB,2026-05-13T21:30:50.865Z,8,"[{'isbn10': '', 'isbn13': '9781954118812'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
4,,https://www.amazon.com/dp/0593135202?tag=thene...,,0,Andy Weir,https://static01.nyt.com/bestsellers/images/97...,400,312,,nyt://book/c11ceffc-2fff-5cb0-98c7-c4a75b2d16bd,...,5,4,,PROJECT HAIL MARY,2026-05-20T22:02:25.385Z,55,"[{'isbn10': '', 'isbn13': '9780593135228'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27

In [32]:
bestselling_books_df.tail()

,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,book_uri,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
10,,https://www.amazon.com/dp/0062956388?tag=thene...,,0,Lynsay Sands,https://static01.nyt.com/bestsellers/images/97...,500,331,,nyt://book/a37aebd8-9bd3-50ad-a2fd-27f8882ee73e,...,11,0,,IMMORTAL ANGEL,2026-03-06T09:04:51.486Z,1,"[{'isbn10': '', 'isbn13': '9780062956279'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
11,,https://www.amazon.com/dp/1496729129?tag=thene...,,0,Joanne Fluke,https://static01.nyt.com/bestsellers/images/97...,500,354,,nyt://book/c628e428-03bc-5bc2-9e33-3827259145b6,...,12,0,,CHRISTMAS CUPCAKE MURDER,2026-03-06T09:04:52.682Z,1,"[{'isbn10': '', 'isbn13': '9781496729149'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
12,,https://www.amazon.com/dp/0316498939?tag=thene...,,0,Robert Galbraith,https://static01.nyt.com/bestsellers/images/97...,500,330,,nyt://book/d0520287-a2d9-5c36-8f21-71de1f9138f2,...,13,8,,TROUBLED BLOOD,2026-03-06T08:56:38.657Z,3,"[{'isbn10': '', 'isbn13': '9780316498968'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
13,,https://www.amazon.com/dp/150118881X?tag=thene...,,0,Ruth Ware,https://static01.nyt.com/bestsellers/images/97...,500,331,,nyt://book/603b3844-b7e7-5f0b-b32c-0d760002f659,...,14,10,,ONE BY ONE,2026-03-06T09:09:02.774Z,4,"[{'isbn10': '', 'isbn13': '9781501188817'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
14,,https://www.amazon.com/dp/0525559477?tag=thene...,,0,Matt Haig,https://static01.nyt.com/bestsellers/images/97...,500,331,,nyt://book/60d0ee2d-3d05-50c9-a484-050d17a2308e,...,15,0,,THE MIDNIGHT LIBRARY,2026-03-06T03:15:23.815Z,1,"[{'isbn10': '', 'isbn13': '9780525559474'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03

## Exporting the data to a csv

In [33]:
bestselling_books_df.to_csv("raw_data/raw_data.csv")

## Repeating the process across multiple days of data collection

Gathering even more historical data the next day (API calls are limited to nyt)

In [44]:
# Setting a variable to make sure the loop doesn't use all my API calls 
number_of_calls = 450

# Setting up the last date I have
current = "2020-10-18"

# Setting up an empty url variable for my calls
url = ""

# Setting up an empty variable for the date of the previous list
previous_published_date = ""

for i in range(number_of_calls):
    
    # if it is the first call, use the specific request for the current list so that we can get the dates
    if i == 0:
        url = f"https://api.nytimes.com/svc/books/v3/lists/{current}/combined-print-and-e-book-fiction.json?api-key={api_key}"
        response = requests.get(url)
        bestseller_list = response.json()

        # getting the date info I need for the next call
        previous_published_date = bestseller_list["results"]["previous_published_date"]
        # print(previous_published_date)
        
        # Getting the dataset I need
        bestselling_books = bestseller_list["results"]["books"]
        # print(bestselling_books[0])

        # Create a dataframe with the list of books
        bestselling_books_df = pd.json_normalize(bestselling_books)

        # Adding the additional columns with dates that I need
        published_date = bestseller_list["results"]["published_date"]
        bestselling_books_df["published_date"] = published_date

        bestsellers_date = bestseller_list["results"]["bestsellers_date"]
        bestselling_books_df["bestsellers_date"] = bestsellers_date

        # Since this will run a while, I am going to print to let myself know it worked
        print("Call 1 done")

        # Adding 12 seconds of sleep so as to not exceed the NYT call limit
        sleep(12)
        
    # For the answer other than the first call, use the date previous_published_date to call the previous list
    else: 
        url = f"https://api.nytimes.com/svc/books/v3/lists/{previous_published_date}/combined-print-and-e-book-fiction.json?api-key={api_key}"
        response = requests.get(url)
        bestseller_list = response.json()

        # getting the date info I need
        previous_published_date = bestseller_list["results"]["previous_published_date"]
        # print(previous_published_date)

        # Printing the info I need to check this worked
        bestselling_books = bestseller_list["results"]["books"]
        # print(bestselling_books[0])

        # Creating a new dataframe with the new list 
        new_bestselling_books_df = pd.json_normalize(bestselling_books)

        published_date = bestseller_list["results"]["published_date"]
        new_bestselling_books_df["published_date"] = published_date

        bestsellers_date = bestseller_list["results"]["bestsellers_date"]
        new_bestselling_books_df["bestsellers_date"] = bestsellers_date

        # Appending the new dataframe to the master data frame
        bestselling_books_df = pd.concat([bestselling_books_df, new_bestselling_books_df])

        # Since this will run a while, I am going to print to let myself know it worked
        print(f"Call {i} done")

        # Adding 12 seconds of sleep so as to not exceed the NYT call limit
        sleep(12)

Call 1 done
Call 1 done
Call 2 done
Call 3 done
Call 4 done
Call 5 done
Call 6 done
Call 7 done
Call 8 done
Call 9 done
Call 10 done
Call 11 done
Call 12 done
Call 13 done
Call 14 done
Call 15 done
Call 16 done
Call 17 done
Call 18 done
Call 19 done
Call 20 done
Call 21 done
Call 22 done
Call 23 done
Call 24 done
Call 25 done
Call 26 done
Call 27 done
Call 28 done
Call 29 done
Call 30 done
Call 31 done
Call 32 done
Call 33 done
Call 34 done
Call 35 done
Call 36 done
Call 37 done
Call 38 done
Call 39 done
Call 40 done
Call 41 done
Call 42 done
Call 43 done
Call 44 done
Call 45 done
Call 46 done
Call 47 done
Call 48 done
Call 49 done
Call 50 done
Call 51 done
Call 52 done
Call 53 done
Call 54 done
Call 55 done
Call 56 done
Call 57 done
Call 58 done
Call 59 done
Call 60 done
Call 61 done
Call 62 done
Call 63 done
Call 64 done
Call 65 done
Call 66 done
Call 67 done
Call 68 done
Call 69 done
Call 70 done
Call 71 done
Call 72 done
Call 73 done
Call 74 done
Call 75 done
Call 76 done
Call 77 done
Call 78 done
Call 79 done
Call 80 done
Call 81 done
Call 82 done
Call 83 done
Call 84 done
Call 85 done
Call 86 done
Call 87 done
Call 88 done
Call 89 done
Call 90 done
Call 91 done
Call 92 done
Call 93 done
Call 94 done
Call 95 done
Call 96 done
Call 97 done
Call 98 done
Call 99 done
Call 100 done
Call 101 done
Call 102 done
Call 103 done
Call 104 done
Call 105 done
Call 106 done
Call 107 done
Call 108 done
Call 109 done
Call 110 done
Call 111 done
Call 112 done
Call 113 done
Call 114 done
Call 115 done
Call 116 done
Call 117 done
Call 118 done
Call 119 done
Call 120 done
Call 121 done
Call 122 done
Call 123 done
Call 124 done
Call 125 done
Call 126 done
Call 127 done
Call 128 done
Call 129 done
Call 130 done
Call 131 done
Call 132 done
Call 133 done
Call 134 done
Call 135 done
Call 136 done
Call 137 done
Call 138 done
Call 139 done
Call 140 done
Call 141 done
Call 142 done
Call 143 done
Call 144 done
Call 145 done
Call 146 done
Call 147 done
Call 148 done
Call 149 done
Call 150 done
Call 151 done
Call 152 done
Call 153 done
Call 154 done
Call 155 done
Call 156 done
Call 157 done
Call 158 done
Call 159 done
Call 160 done
Call 161 done
Call 162 done
Call 163 done
Call 164 done
Call 165 done
Call 166 done
Call 167 done
Call 168 done
Call 169 done
Call 170 done
Call 171 done
Call 172 done
Call 173 done
Call 174 done
Call 175 done
Call 176 done
Call 177 done
Call 178 done
Call 179 done
Call 180 done
Call 181 done
Call 182 done
Call 183 done
Call 184 done
Call 185 done
Call 186 done
Call 187 done
Call 188 done
Call 189 done
Call 190 done
Call 191 done
Call 192 done
Call 193 done
Call 194 done
Call 195 done
Call 196 done
Call 197 done
Call 198 done
Call 199 done
Call 200 done
Call 201 done
Call 202 done
Call 203 done
Call 204 done
Call 205 done
Call 206 done
Call 207 done
Call 208 done
Call 209 done
Call 210 done
Call 211 done
Call 212 done
Call 213 done
Call 214 done
Call 215 done
Call 216 done
Call 217 done
Call 218 done
Call 219 done
Call 220 done
Call 221 done
Call 222 done
Call 223 done
Call 224 done
Call 225 done
Call 226 done
Call 227 done
Call 228 done
Call 229 done
Call 230 done
Call 231 done
Call 232 done
Call 233 done
Call 234 done
Call 235 done
Call 236 done
Call 237 done
Call 238 done
Call 239 done
Call 240 done
Call 241 done
Call 242 done
Call 243 done
Call 244 done
Call 245 done
Call 246 done
Call 247 done
Call 248 done
Call 249 done
Call 250 done
Call 251 done
Call 252 done
Call 253 done
Call 254 done
Call 255 done
Call 256 done
Call 257 done
Call 258 done
Call 259 done
Call 260 done
Call 261 done
Call 262 done
Call 263 done
Call 264 done
Call 265 done
Call 266 done
Call 267 done
Call 268 done
Call 269 done
Call 270 done
Call 271 done
Call 272 done
Call 273 done
Call 274 done
Call 275 done
Call 276 done
Call 277 done
Call 278 done
Call 279 done
Call 280 done
Call 281 done
Call 282 done
Call 283 done
Call 284 done
Call 285 done
Call 286 done
Call 287 done
Call 288 done
Call 289 done
Call 290 done
Call 291 done
Call 292 done
Call 293 done
Call 294 done
Call 295 done
Call 296 done
Call 297 done
Call 298 done
Call 299 done
Call 300 done
Call 301 done
Call 302 done
Call 303 done
Call 304 done
Call 305 done
Call 306 done
Call 307 done
Call 308 done
Call 309 done
Call 310 done
Call 311 done
Call 312 done
Call 313 done
Call 314 done
Call 315 done
Call 316 done
Call 317 done
Call 318 done
Call 319 done
Call 320 done
Call 321 done
Call 322 done
Call 323 done
Call 324 done
Call 325 done
Call 326 done
Call 327 done
Call 328 done
Call 329 done
Call 330 done
Call 331 done
Call 332 done
Call 333 done
Call 334 done
Call 335 done
Call 336 done
Call 337 done
Call 338 done
Call 339 done
Call 340 done
Call 341 done
Call 342 done
Call 343 done
Call 344 done
Call 345 done
Call 346 done
Call 347 done
Call 348 done
Call 349 done
Call 350 done
Call 351 done
Call 352 done
Call 353 done
Call 354 done
Call 355 done
Call 356 done
Call 357 done
Call 358 done
Call 359 done
Call 360 done
Call 361 done
Call 362 done
Call 363 done
Call 364 done
Call 365 done
Call 366 done
Call 367 done
Call 368 done
Call 369 done
Call 370 done
Call 371 done
Call 372 done
Call 373 done
Call 374 done
Call 375 done
Call 376 done
Call 377 done
Call 378 done
Call 379 done
Call 380 done
Call 381 done
Call 382 done
Call 383 done
Call 384 done
Call 385 done
Call 386 done
Call 387 done
Call 388 done
Call 389 done
Call 390 done
Call 391 done
Call 392 done
Call 393 done
Call 394 done
Call 395 done
Call 396 done
Call 397 done
Call 398 done
Call 399 done
Call 400 done
Call 401 done
Call 402 done
Call 403 done
Call 404 done
Call 405 done
Call 406 done
Call 407 done
Call 408 done
Call 409 done
Call 410 done
Call 411 done
Call 412 done
Call 413 done
Call 414 done
Call 415 done
Call 416 done
Call 417 done
Call 418 done
Call 419 done
Call 420 done
Call 421 done
Call 422 done
Call 423 done
Call 424 done
Call 425 done
Call 426 done
Call 427 done
Call 428 done
Call 429 done
Call 430 done
Call 431 done
Call 432 done
Call 433 done
Call 434 done
Call 435 done
Call 436 done
Call 437 done
Call 438 done
Call 439 done
Call 440 done
Call 441 done
Call 442 done
Call 443 done
Call 444 done
Call 445 done
Call 446 done
Call 447 done
Call 448 done
Call 449 done

In [45]:
bestselling_books_df.shape

(9310, 30)

In [48]:
bestselling_books_df.head()

,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,book_uri,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
0,,https://www.amazon.com/dp/1538728575?tag=thene...,,0,Nicholas Sparks,https://static01.nyt.com/bestsellers/images/97...,500,329,,nyt://book/b9bf792c-a853-54ce-8f33-7117f51be365,...,1,0,,THE RETURN,2026-03-06T09:36:07.62Z,1,"[{'isbn10': '', 'isbn13': '9781538728574'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
1,,https://www.amazon.com/dp/0593199308?tag=thene...,,0,Jim Butcher,https://static01.nyt.com/bestsellers/images/97...,500,331,,nyt://book/0ef41f25-7ccc-52eb-bef9-265e6e0cd6dc,...,2,0,,BATTLE GROUND,2026-03-06T09:04:31.599Z,1,"[{'isbn10': '', 'isbn13': '9780593199329'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
2,,https://www.amazon.com/dp/0525954988?tag=thene...,,0,Ken Follett,https://static01.nyt.com/bestsellers/images/97...,500,329,,nyt://book/6fd2cc42-7bff-59a1-9c5c-20514172cf5b,...,3,3,,THE EVENING AND THE MORNING,2026-03-06T08:57:01.774Z,3,"[{'isbn10': '', 'isbn13': '9780525954989'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
3,,https://www.amazon.com/dp/1982167289?tag=thene...,,0,Lana Del Rey,https://static01.nyt.com/bestsellers/images/97...,500,326,,nyt://book/d510e3d5-f83b-50b5-9c1b-c386af482ee8,...,4,0,,VIOLET BENT BACKWARDS OVER THE GRASS,2026-03-06T09:04:34.223Z,1,"[{'isbn10': '', 'isbn13': '9781982167288'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4,,https://www.amazon.com/dp/198481835X?tag=thene...,,0,Jodi Picoult,https://static01.nyt.com/bestsellers/images/97...,500,329,,nyt://book/24ac761d-3017-5b80-84f7-0718f5cead02,...,5,1,,THE BOOK OF TWO WAYS,2026-03-06T08:58:44.104Z,2,"[{'isbn10': '', 'isbn13': '9781984818355'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03

In [47]:
# Saving the second batch of raw data
bestselling_books_df.to_csv("raw_data/raw_data_1.csv")

Repeating the process a 3rd time to get as much data as possible. However, only around 50 calls were made because the structure of the historic data changed. This didn't matter too much as I already have a decade of data

In [15]:
# Setting a variable to make sure the loop doesn't use all my API calls 
number_of_calls = 480

# Setting up the last date I have
current = "2012-03-11"

# Setting up an empty url variable for my calls
url = ""

# Setting up an empty variable for the date of the previous list
previous_published_date = ""

for i in range(number_of_calls):
    
    # if it is the first call, use the specific request for the current list so that we can get the dates
    if i == 0:
        url = f"https://api.nytimes.com/svc/books/v3/lists/{current}/combined-print-and-e-book-fiction.json?api-key={api_key}"
        response = requests.get(url)
        bestseller_list = response.json()

        # getting the date info I need for the next call
        previous_published_date = bestseller_list["results"]["previous_published_date"]
        # print(previous_published_date)
        
        # Getting the dataset I need
        bestselling_books = bestseller_list["results"]["books"]
        # print(bestselling_books[0])

        # Create a dataframe with the list of books
        bestselling_books_df = pd.json_normalize(bestselling_books)

        # Adding the additional columns with dates that I need
        published_date = bestseller_list["results"]["published_date"]
        bestselling_books_df["published_date"] = published_date

        bestsellers_date = bestseller_list["results"]["bestsellers_date"]
        bestselling_books_df["bestsellers_date"] = bestsellers_date

        # Since this will run a while, I am going to print to let myself know it worked
        print("Call 1 done")

        # Adding 12 seconds of sleep so as to not exceed the NYT call limit
        sleep(12)
        
    # For the answer other than the first call, use the date previous_published_date to call the previous list
    else: 
        url = f"https://api.nytimes.com/svc/books/v3/lists/{previous_published_date}/combined-print-and-e-book-fiction.json?api-key={api_key}"
        response = requests.get(url)
        bestseller_list = response.json()

        # getting the date info I need
        previous_published_date = bestseller_list["results"]["previous_published_date"]
        # print(previous_published_date)

        # Printing the info I need to check this worked
        bestselling_books = bestseller_list["results"]["books"]
        # print(bestselling_books[0])

        # Creating a new dataframe with the new list 
        new_bestselling_books_df = pd.json_normalize(bestselling_books)

        published_date = bestseller_list["results"]["published_date"]
        new_bestselling_books_df["published_date"] = published_date

        bestsellers_date = bestseller_list["results"]["bestsellers_date"]
        new_bestselling_books_df["bestsellers_date"] = bestsellers_date

        # Appending the new dataframe to the master data frame
        bestselling_books_df = pd.concat([bestselling_books_df, new_bestselling_books_df])

        # Since this will run a while, I am going to print to let myself know it worked
        print(f"Call {i} done")

        # Adding 12 seconds of sleep so as to not exceed the NYT call limit
        sleep(12)

Call 1 done
Call 1 done
Call 2 done
Call 3 done
Call 4 done
Call 5 done
Call 6 done
Call 7 done
Call 8 done
Call 9 done
Call 10 done
Call 11 done
Call 12 done
Call 13 done
Call 14 done
Call 15 done
Call 16 done
Call 17 done
Call 18 done
Call 19 done
Call 20 done
Call 21 done
Call 22 done
Call 23 done
Call 24 done
Call 25 done
Call 26 done
Call 27 done
Call 28 done
Call 29 done
Call 30 done
Call 31 done
Call 32 done
Call 33 done
Call 34 done
Call 35 done
Call 36 done
Call 37 done
Call 38 done
Call 39 done
Call 40 done
Call 41 done
Call 42 done
Call 43 done
Call 44 done
Call 45 done
Call 46 done
Call 47 done
Call 48 done
Call 49 done
Call 50 done
Call 51 done
Call 52 done
Call 53 done
Call 54 done

KeyError: 'previous_published_date'

In [17]:
bestselling_books_df.head()

,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,book_uri,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
0,,http://www.amazon.com/Celebrity-Death-J-D-Robb...,,0,J. D. Robb,https://static01.nyt.com/bestsellers/images/97...,495,307,,nyt://book/d1ec5779-c211-581e-a118-572a3b136be8,...,1,0,,CELEBRITY IN DEATH,2026-03-07T17:21:15.669Z,1,"[{'isbn10': '', 'isbn13': '9781101560365'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
1,,http://www.amazon.com/Girl-Kicked-Hornets-Mill...,,0,Stieg Larsson,https://static01.nyt.com/bestsellers/images/97...,485,330,https://www.nytimes.com/2010/05/21/books/21boo...,nyt://book/69a936f5-8e65-5843-a4bd-bd5de4e042a7,...,2,10,https://www.nytimes.com/2010/05/30/books/revie...,THE GIRL WHO KICKED THE HORNET’S NEST,2026-03-07T17:21:17.058Z,27,"[{'isbn10': '', 'isbn13': '9780307454560'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
2,,http://www.amazon.com/Perfect-Blood-Hollows-Ki...,,0,Kim Harrison,https://storage.googleapis.com/du-prd/books/im...,193,128,,nyt://book/67827cb7-ad3d-5a80-8c6d-cf825d575d71,...,3,0,,A PERFECT BLOOD,2026-03-07T17:25:37.867Z,1,"[{'isbn10': '', 'isbn13': '9780062101020'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
3,,http://www.amazon.com/Kill-Shot-American-Assas...,,0,Vince Flynn,https://static01.nyt.com/bestsellers/images/97...,495,323,,nyt://book/4bcb310d-405c-5501-9c98-13ecd4ef8e0e,...,4,2,,KILL SHOT,2026-03-07T17:15:10.306Z,3,"[{'isbn10': '', 'isbn13': '9781439100523'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
4,,http://www.amazon.com/Defending-Jacob-Novel-Wi...,,0,William Landay,https://static01.nyt.com/bestsellers/images/97...,495,300,https://www.nytimes.com/2012/02/13/books/defen...,nyt://book/a89e4199-b517-571b-8bfb-8429fa7831c4,...,5,4,,DEFENDING JACOB,2026-03-07T10:12:01.817Z,4,"[{'isbn10': '', 'isbn13': '9780345527592'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25

In [18]:
bestseller_list

{'status': 'OK',
 'copyright': 'Copyright (c) 2026 The New York Times Company. All Rights Reserved.',
 'num_results': 20,
 'last_modified': '2025-05-19T21:17:07Z',
 'results': {'display_name': 'Combined Print Fiction',
  'list_name': 'Combined Print Fiction',
  'list_name_encoded': 'combined-print-and-e-book-fiction',
  'published_date': '2011-02-20',
  'next_published_date': '2011-02-27',
  'bestsellers_date': '2011-02-05',
  'normal_list_ends_at': 20,
  'updated': 'WEEKLY',
  'list_id': 705,
  'uri': 'nyt://bestsellerslist/7ad7a805-82c5-545e-bbf2-450174529d2f',
  'books': [{'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/Tick-Tock-Michael-Bennett-Book-ebook/dp/B0047Y16MG?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'James Patterson and Michael Ledwidge',
    'book_image': '',
    'book_image_height': 0,
    'book_image_width': 0,
    'book_review_link': '',
    'book_uri': 'nyt://book/bd4cdccd-0040-537e-b567-f9fd4ebf031f',
    'contributor': 'by James Patterson and Michael Ledwidge',
    'contributor_note': '',
    'created_date': '2026-07-07T16:14:02.281Z',
    'dagger': 0,
    'description': 'The New York detective Michael Bennett enlists the help of a former colleague to solve a rash of horrifying crimes that are throwing the city into chaos.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780316129183',
    'publisher': 'Little, Brown',
    'rank': 1,
    'rank_last_week': 1,
    'sunday_review_link': '',
    'title': 'TICK TOCK',
    'updated_date': '2026-07-07T16:14:02.281Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780316129183'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/Tick-Tock-Michael-Bennett-Book-ebook/dp/B0047Y16MG?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780316129183?at=10lIEQ'},
     {'name': 'Barnes and Noble',
      'url': 'https://www.barnesandnoble.com/w/?ean=9780316129183'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTICK%2BTOCK%2FJames%2BPatterson%2Band%2BMichael%2BLedwidge%2F9780316129183'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780316129183'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/Girl-Dragon-Tattoo-Stieg-Larsson/dp/0307269752?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Stieg Larsson',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780307272119.jpg',
    'book_image_height': 495,
    'book_image_width': 277,
    'book_review_link': 'https://www.nytimes.com/2008/09/30/books/30kaku.html',
    'book_uri': 'nyt://book/61741728-91b7-59e6-b70e-61e4e41c4a1f',
    'contributor': 'by Stieg Larsson',
    'contributor_note': '',
    'created_date': '2026-07-07T20:18:24.575Z',
    'dagger': 0,
    'description': 'A hacker and a journalist investigate the disappearance of a Swedish heiress 40 years earlier.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780307272119',
    'publisher': 'Knopf Doubleday',
    'rank': 2,
    'rank_last_week': 2,
    'sunday_review_link': 'https://www.nytimes.com/2008/09/14/books/review/Berenson-t.html',
    'title': 'THE GIRL WITH THE DRAGON TATTOO',
    'updated_date': '2026-07-07T20:18:24.575Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780307272119'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/Girl-Dragon-Tattoo-Stieg-Larsson/dp/0307269752?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780307272119?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780307272119&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-girl-with-the-dragon-tattoo-stieg-larsson%2F1100040490%3Fean%3D9780307272119&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTHE%2BGIRL%2BWITH%2BTHE%2BDRAGON%2BTATTOO%2FStieg%2BLarsson%2F9780307272119'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780307272119'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/Girl-Played-Fire-Millennium-Trilogy/dp/0307476154?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Stieg Larsson',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780307272300.jpg',
    'book_image_height': 495,
    'book_image_width': 302,
    'book_review_link': 'https://www.nytimes.com/2009/07/17/books/17book.html',
    'book_uri': 'nyt://book/78e173e0-3f3f-567c-9119-31903e99c419',
    'contributor': 'by Stieg Larsson',
    'contributor_note': '',
    'created_date': '2026-07-07T20:18:27.338Z',
    'dagger': 0,
    'description': 'In the second volume of the Millennium trilogy, a Swedish hacker becomes a murder suspect.',
    'first_chapter_link': 'https://www.nytimes.com/2009/07/17/books/excerpt-girl-who-played-with-fire.html',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780307272300',
    'publisher': 'Knopf Doubleday',
    'rank': 3,
    'rank_last_week': 3,
    'sunday_review_link': 'https://www.nytimes.com/2009/08/16/books/review/Crime-t.html',
    'title': 'THE GIRL WHO PLAYED WITH FIRE',
    'updated_date': '2026-07-07T20:18:27.338Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780307272300'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/Girl-Played-Fire-Millennium-Trilogy/dp/0307476154?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780307272300?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780307272300&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-girl-who-played-with-fire-stieg-larsson%2F1100160513%3Fean%3D9780307272300&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTHE%2BGIRL%2BWHO%2BPLAYED%2BWITH%2BFIRE%2FStieg%2BLarsson%2F9780307272300'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780307272300'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/Girl-Kicked-Hornets-Millennium-Trilogy/dp/030726999X?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Stieg Larsson',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780307593672.jpg',
    'book_image_height': 485,
    'book_image_width': 330,
    'book_review_link': 'https://www.nytimes.com/2010/05/21/books/21book.html',
    'book_uri': 'nyt://book/7578b5a7-1d29-53c5-a6c8-618672c92f9f',
    'contributor': 'by Stieg Larsson',
    'contributor_note': '',
    'created_date': '2026-07-07T20:18:23.221Z',
    'dagger': 0,
    'description': 'The third volume of the Millennium trilogy, about a Swedish hacker and a journalist.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780307593672',
    'publisher': 'Knopf Doubleday',
    'rank': 4,
    'rank_last_week': 4,
    'sunday_review_link': 'https://www.nytimes.com/2010/05/30/books/review/Kamp-t.html',
    'title': 'THE GIRL WHO KICKED THE HORNET’S NEST',
    'updated_date': '2026-07-07T20:18:23.221Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780307593672'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/Girl-Kicked-Hornets-Millennium-Trilogy/dp/030726999X?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780307593672?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780307593672&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-girl-who-kicked-the-hornets-nest-stieg-larsson%2F1100160449%3Fean%3D9780307593672&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTHE%2BGIRL%2BWHO%2BKICKED%2BTHE%2BHORNET%25E2%2580%2599S%2BNEST%2FStieg%2BLarsson%2F9780307593672'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780307593672'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/Water-Elephants-Sara-Gruen/dp/1616200715?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Sara Gruen',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9781565125858.jpg',
    'book_image_height': 280,
    'book_image_width': 174,
    'book_review_link': 'https://www.nytimes.com/2007/07/11/books/11elep.html',
    'book_uri': 'nyt://book/6b229731-cd83-5af7-ae22-90b66ace811c',
    'contributor': 'by Sara Gruen',
    'contributor_note': '',
    'created_date': '2026-07-07T20:25:46.49Z',
    'dagger': 0,
    'description': 'After his parents die in a car accident, young veterinary student — and an elephant — save a Depression-era circus.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9781565125858',
    'publisher': 'Algonquin',
    'rank': 5,
    'rank_last_week': 5,
    'sunday_review_link': 'https://www.nytimes.com/2006/06/04/books/review/04judd.html',
    'title': 'WATER FOR ELEPHANTS',
    'updated_date': '2026-07-07T20:25:46.49Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9781565125858'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/Water-Elephants-Sara-Gruen/dp/1616200715?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9781565125858?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9781565125858&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fwater-for-elephants-sara-gruen%2F1100219254%3Fean%3D9781565125858&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FWATER%2BFOR%2BELEPHANTS%2FSara%2BGruen%2F9781565125858'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9781565125858'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/Cutting-Stone-novel-Abraham-Verghese/dp/0375414495?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Abraham Verghese',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780307271341.jpg',
    'book_image_height': 325,
    'book_image_width': 200,
    'book_review_link': '',
    'book_uri': 'nyt://book/f238789c-6d41-550c-b9d0-2f9e5c014b83',
    'contributor': 'by Abraham Verghese',
    'contributor_note': '',
    'created_date': '2026-07-07T20:21:48.545Z',
    'dagger': 0,
    'description': 'Twin brothers, conjoined at birth and then separated, grow up amid the political turmoil of Ethiopia.',
    'first_chapter_link': 'https://www.nytimes.com/2009/02/08/books/chapters/chapter-cutting-for-stone.html',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780307271341',
    'publisher': 'Knopf Doubleday',
    'rank': 6,
    'rank_last_week': 7,
    'sunday_review_link': 'https://www.nytimes.com/2009/02/08/books/review/Wagner-t.html',
    'title': 'CUTTING FOR STONE',
    'updated_date': '2026-07-07T20:21:48.545Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780307271341'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/Cutting-Stone-novel-Abraham-Verghese/dp/0375414495?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780307271341?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780307271341&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fcutting-for-stone-abraham-verghese%2F1100047420%3Fean%3D9780307271341&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FCUTTING%2BFOR%2BSTONE%2FAbraham%2BVerghese%2F9780307271341'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780307271341'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/The-Help-Kathryn-Stockett/dp/0425232204?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Kathryn Stockett',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9781440697661.jpg',
    'book_image_height': 440,
    'book_image_width': 330,
    'book_review_link': 'https://www.nytimes.com/2009/02/19/books/19masl.html',
    'book_uri': 'nyt://book/1ef97da5-291d-501a-9744-a4e99dd101c5',
    'contributor': 'by Kathryn Stockett',
    'contributor_note': '',
    'created_date': '2026-07-07T20:18:34.793Z',
    'dagger': 0,
    'description': 'Three women — a white socialite and two black maids — work on a tell-all book about black domestic servants in 1960s Mississippi.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9781440697661',
    'publisher': 'Penguin Group',
    'rank': 7,
    'rank_last_week': 9,
    'sunday_review_link': '',
    'title': 'THE HELP',
    'updated_date': '2026-07-07T20:18:34.793Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9781440697661'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/The-Help-Kathryn-Stockett/dp/0425232204?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9781440697661?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9781440697661&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-help-kathryn-stockett%2F1100036619%3Fean%3D9781440697661&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTHE%2BHELP%2FKathryn%2BStockett%2F9781440697661'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9781440697661'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/The-Confession-Novel-John-Grisham/dp/0385528043?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'John Grisham',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780385534130.jpg',
    'book_image_height': 495,
    'book_image_width': 276,
    'book_review_link': 'https://www.nytimes.com/2010/11/08/books/08book.html',
    'book_uri': 'nyt://book/52a899e3-5775-57f1-b4e0-739c224f083a',
    'contributor': 'by John Grisham',
    'contributor_note': '',
    'created_date': '2026-07-07T20:18:40.606Z',
    'dagger': 0,
    'description': "A man who committed a despicable crime but allowed another to be sent to death row in his place now wants to admit his guilt, but must convince the authorities he's telling the truth.",
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780385534130',
    'publisher': 'Knopf Doubleday',
    'rank': 8,
    'rank_last_week': 6,
    'sunday_review_link': '',
    'title': 'THE CONFESSION',
    'updated_date': '2026-07-07T20:18:40.606Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780385534130'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/The-Confession-Novel-John-Grisham/dp/0385528043?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780385534130?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://barnesandnoble.sjv.io/c/197432/1961179/22009?prodsku=9780385534130&u=https%3A%2F%2Fwww.barnesandnoble.com%2Fw%2Fthe-confession-john-grisham%2F1100040141%3Fean%3D9780385534130&intsrc=APIG_15890'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTHE%2BCONFESSION%2FJohn%2BGrisham%2F9780385534130'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780385534130'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/Marrying-Daisy-Bellamy-Lakeshore-Chronicles/dp/0778329259?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Susan Wiggs',
    'book_image': 'https://static01.nyt.com/bestsellers/images/9780778329251.jpg',
    'book_image_height': 440,
    'book_image_width': 330,
    'book_review_link': '',
    'book_uri': 'nyt://book/df213333-56ee-549c-916c-4df7be013ba7',
    'contributor': 'by Susan Wiggs',
    'contributor_note': '',
    'created_date': '2026-07-07T20:25:47.762Z',
    'dagger': 0,
    'description': 'A woman struggles for years to choose between two men, one honorable and steady, one wild and untethered. And then, one fateful day, the decision is made for her.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780778329251',
    'publisher': 'Mira',
    'rank': 9,
    'rank_last_week': 8,
    'sunday_review_link': '',
    'title': 'MARRYING DAISY BELLAMY',
    'updated_date': '2026-07-07T20:25:47.762Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780778329251'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/Marrying-Daisy-Bellamy-Lakeshore-Chronicles/dp/0778329259?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780778329251?at=10lIEQ'},
     {'name': 'Barnes & Noble',
      'url': 'https://www.barnesandnoble.com/s/MARRYING%20DAISY%20BELLAMY'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FMARRYING%2BDAISY%2BBELLAMY%2FSusan%2BWiggs%2F9780778329251'},
     {'name': 'Bookshop.org',
      'url': 'https://bookshop.org/a/3546/9780778329251'}]},
   {'age_group': '',
    'amazon_product_url': 'http://www.amazon.com/The-Inner-Circle-Brad-Meltzer-ebook/dp/B0047Y174I?tag=thenewyorktim-20',
    'article_chapter_link': '',
    'asterisk': 0,
    'author': 'Brad Meltzer',
    'book_image': '',
    'book_image_height': 0,
    'book_image_width': 0,
    'book_review_link': '',
    'book_uri': 'nyt://book/5396a5d2-7af9-53ba-99c0-8c272e8332a4',
    'contributor': 'by Brad Meltzer',
    'contributor_note': '',
    'created_date': '2026-07-07T16:12:21.286Z',
    'dagger': 0,
    'description': 'An archivist discovers a book that once belonged to George Washington and conceals a deadly secret.',
    'first_chapter_link': '',
    'price': '0.00',
    'primary_isbn10': '',
    'primary_isbn13': '9780446582636',
    'publisher': 'Grand Central',
    'rank': 10,
    'rank_last_week': 10,
    'sunday_review_link': '',
    'title': 'THE INNER CIRCLE',
    'updated_date': '2026-07-07T16:12:21.286Z',
    'weeks_on_list': 2,
    'isbns': [{'isbn10': '', 'isbn13': '9780446582636'}],
    'buy_links': [{'name': 'Amazon',
      'url': 'http://www.amazon.com/The-Inner-Circle-Brad-Meltzer-ebook/dp/B0047Y174I?tag=thenewyorktim-20'},
     {'name': 'Apple Books',
      'url': 'https://goto.applebooks.apple/9780446582636?at=10lIEQ'},
     {'name': 'Barnes and Noble',
      'url': 'https://www.barnesandnoble.com/w/?ean=9780446582636'},
     {'name': 'Books-A-Million',
      'url': 'https://www.anrdoezrs.net/click-7990613-35140?url=https%3A%2F%2Fwww.booksamillion.com%2Fp%2FTHE%2BINNER%2BCIRCLE%2FBrad%2BMeltzer%2F9780446582636'},

In [19]:
bestselling_books_df.to_csv("raw_data/raw_data_2.csv")