# Merging the two datasets

## Importing packages and the data sets

In [2]:
import pandas as pd

In [3]:
data_from_2020 = pd.read_csv('raw_data/raw_data.csv')
data_from_2012 = pd.read_csv('raw_data/raw_data_1.csv')

## Checking everything looks as expected

In [4]:
data_from_2020.shape

(4500, 31)

In [5]:
data_from_2020.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            4500 non-null   int64
 1   age_group             0 non-null      float64
 2   amazon_product_url    4497 non-null   str
 3   article_chapter_link  0 non-null      float64
 4   asterisk              4500 non-null   int64
 5   author                4497 non-null   str
 6   book_image            4497 non-null   str
 7   book_image_height     4500 non-null   int64
 8   book_image_width      4500 non-null   int64
 9   book_review_link      91 non-null     str
 10  book_uri              4500 non-null   str
 11  contributor           4497 non-null   str
 12  contributor_note      6 non-null      str
 13  created_date          4500 non-null   str
 14  dagger                4500 non-null   int64
 15  description           4497 non-null   str
 16  first_chapter_link    0 non-null      float64
 17  price                 4500 non-null   float64
 18  primary_isbn10        0 non-null      float64
 19  primary_isbn13        4500 non-null   int64
 20  publisher             4497 non-null   str
 21  rank                  4500 non-null   int64
 22  rank_last_week        4500 non-null   int64
 23  sunday_review_link    51 non-null     str
 24  title                 4500 non-null   str
 25  updated_date          4500 non-null   str
 26  weeks_on_list         4500 non-null   int64
 27  isbns                 4500 non-null   str
 28  buy_links             4500 non-null   str
 29  published_date        4500 non-null   str
 30  bestsellers_date      4500 non-null   str
dtypes: float64(5), int64(9), str(17)
memory usage: 1.1 MB

In [6]:
data_from_2012.shape

(9310, 31)

In [7]:
data_from_2012.info()

<class 'pandas.DataFrame'>
RangeIndex: 9310 entries, 0 to 9309
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            9310 non-null   int64
 1   age_group             0 non-null      float64
 2   amazon_product_url    9310 non-null   str
 3   article_chapter_link  0 non-null      float64
 4   asterisk              9310 non-null   int64
 5   author                9310 non-null   str
 6   book_image            9281 non-null   str
 7   book_image_height     9310 non-null   int64
 8   book_image_width      9310 non-null   int64
 9   book_review_link      1546 non-null   str
 10  book_uri              9310 non-null   str
 11  contributor           9310 non-null   str
 12  contributor_note      13 non-null     str
 13  created_date          9310 non-null   str
 14  dagger                9310 non-null   int64
 15  description           9191 non-null   str
 16  first_chapter_link    11 non-null     str
 17  price                 9310 non-null   float64
 18  primary_isbn10        0 non-null      float64
 19  primary_isbn13        9310 non-null   str
 20  publisher             9310 non-null   str
 21  rank                  9310 non-null   int64
 22  rank_last_week        9310 non-null   int64
 23  sunday_review_link    976 non-null    str
 24  title                 9310 non-null   str
 25  updated_date          9310 non-null   str
 26  weeks_on_list         9310 non-null   int64
 27  isbns                 9310 non-null   str
 28  buy_links             9310 non-null   str
 29  published_date        9310 non-null   str
 30  bestsellers_date      9310 non-null   str
dtypes: float64(4), int64(8), str(19)
memory usage: 2.2 MB

## Removing duplicate data

I just want to add raw_data_1 onto the end of raw_data

That will involve getting rid of the first few rows of raw_data_1 as they are duplicates

In [8]:
data_from_2012.head(20)

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
0,0,NaN,https://www.amazon.com/dp/1538728575?tag=thene...,NaN,0,Nicholas Sparks,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,1,0,NaN,THE RETURN,2026-03-06T09:36:07.62Z,1,"[{'isbn10': '', 'isbn13': '9781538728574'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
1,1,NaN,https://www.amazon.com/dp/0593199308?tag=thene...,NaN,0,Jim Butcher,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,2,0,NaN,BATTLE GROUND,2026-03-06T09:04:31.599Z,1,"[{'isbn10': '', 'isbn13': '9780593199329'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
2,2,NaN,https://www.amazon.com/dp/0525954988?tag=thene...,NaN,0,Ken Follett,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,3,3,NaN,THE EVENING AND THE MORNING,2026-03-06T08:57:01.774Z,3,"[{'isbn10': '', 'isbn13': '9780525954989'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
3,3,NaN,https://www.amazon.com/dp/1982167289?tag=thene...,NaN,0,Lana Del Rey,https://static01.nyt.com/bestsellers/images/97...,500,326,NaN,...,4,0,NaN,VIOLET BENT BACKWARDS OVER THE GRASS,2026-03-06T09:04:34.223Z,1,"[{'isbn10': '', 'isbn13': '9781982167288'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4,4,NaN,https://www.amazon.com/dp/198481835X?tag=thene...,NaN,0,Jodi Picoult,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,5,1,NaN,THE BOOK OF TWO WAYS,2026-03-06T08:58:44.104Z,2,"[{'isbn10': '', 'isbn13': '9781984818355'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
5,5,NaN,https://www.amazon.com/dp/0316457426?tag=thene...,NaN,0,James Patterson and J.D. Barker,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,6,2,NaN,THE COAST-TO-COAST MURDERS,2026-03-06T09:12:16.944Z,2,"[{'isbn10': '', 'isbn13': '9780316457422'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
6,6,NaN,https://www.amazon.com/dp/1501190652?tag=thene...,NaN,0,Kyle Mills,https://static01.nyt.com/bestsellers/images/97...,500,327,NaN,...,7,5,NaN,VINCE FLYNN: TOTAL POWER,2026-03-06T09:09:07.476Z,3,"[{'isbn10': '', 'isbn13': '9781501190650'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
7,7,NaN,https://www.amazon.com/dp/1501160834?tag=thene...,NaN,0,Fredrik Backman,https://static01.nyt.com/bestsellers/images/97...,500,332,NaN,...,8,7,NaN,ANXIOUS PEOPLE,2026-03-06T09:36:14.162Z,4,"[{'isbn10': '', 'isbn13': '9781501160837'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
8,8,NaN,https://www.amazon.com/dp/0525536299?tag=thene...,NaN,0,Brit Bennett,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,9,6,NaN,THE VANISHING HALF,2026-03-06T05:54:35.877Z,18,"[{'isbn10': '', 'isbn13': '9780525536291'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
9,9,NaN,https://www.amazon.com/dp/0593128486?tag=thene...,NaN,0,Naomi Novik,https://static01.nyt.com/bestsellers/images/97...,500,333,NaN,...,10,0,NaN,A DEADLY EDUCATION,2026-03-06T09:04:49.547Z,1,"[{'isbn10': '', 'isbn13': '9780593128497'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
10,10,NaN,https://www.amazon.com/dp/0062956388?tag=thene...,NaN,0,Lynsay Sands,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,11,0,NaN,IMMORTAL ANGEL,2026-03-06T09:04:51.486Z,1,"[{'isbn10': '', 'isbn13': '9780062956279'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
11,11,NaN,https://www.amazon.com/dp/1496729129?tag=thene...,NaN,0,Joanne Fluke,https://static01.nyt.com/bestsellers/images/97...,500,354,NaN,...,12,0,NaN,CHRISTMAS CUPCAKE MURDER,2026-03-06T09:04:52.682Z,1,"[{'isbn10': '', 'isbn13': '9781496729149'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
12,12,NaN,https://www.amazon.com/dp/0316498939?tag=thene...,NaN,0,Robert Galbraith,https://static01.nyt.com/bestsellers/images/97...,500,330,NaN,...,13,8,NaN,TROUBLED BLOOD,2026-03-06T08:56:38.657Z,3,"[{'isbn10': '', 'isbn13': '9780316498968'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
13,13,NaN,https://www.amazon.com/dp/150118881X?tag=thene...,NaN,0,Ruth Ware,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,14,10,NaN,ONE BY ONE,2026-03-06T09:09:02.774Z,4,"[{'isbn10': '', 'isbn13': '9781501188817'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
14,14,NaN,https://www.amazon.com/dp/0525559477?tag=thene...,NaN,0,Matt Haig,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,15,0,NaN,THE MIDNIGHT LIBRARY,2026-03-06T03:15:23.815Z,1,"[{'isbn10': '', 'isbn13': '9780525559474'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
15,0,NaN,https://www.amazon.com/dp/198481835X?tag=thene...,NaN,0,Jodi Picoult,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,1,0,NaN,THE BOOK OF TWO WAYS,2026-03-06T08:58:44.104Z,1,"[{'isbn10': '', 'isbn13': '9781984818355'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-11,2020-09-26
16,1,NaN,https://www.amazon.com/dp/0316457426?tag=thene...,NaN,0,James Patterson and J.D. Barker,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,2,0,NaN,THE COAST-TO-COAST MURDERS,2026-03-06T09:12:16.944Z,1,"[{'isbn10': '', 'isbn13': '9780316457422'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-11,2020-09-26
17,2,NaN,https://www.amazon.com/dp/0525954988?tag=thene...,NaN,0,Ken Follett,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,3,1,NaN,THE EVENING AND THE MORNING,2026-03-06T08:57:01.774Z,2,"[{'isbn10': '', 'isbn13': '9780525954989'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-11,2020-09-26
18,3,NaN,https://www.amazon.com/dp/0525522530?tag=thene...,NaN,0,Craig Johnson,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,4,0,NaN,NEXT TO LAST STAND,2026-03-06T08:58:46.539Z,1,"[{'isbn10': '', 'isbn13': '9780525522546'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-11,2020-09-26
19,4,NaN,https://www.amazon.com/dp/1501190652?tag=thene...,NaN,0,Kyle Mills,https://static01.nyt.com/bestsellers/images/97...,500,327,NaN,...,5,2,NaN,VINCE FLYNN: TOTAL POWER,2026-03-06T09:09:07.476Z,2,"[{'isbn10': '', 'isbn13': '9781501190650'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-11,2020-09-26

In [9]:
data_from_2020.tail(20)

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
4480,10,NaN,https://www.amazon.com/dp/0316457426?tag=thene...,NaN,0,James Patterson and J.D. Barker,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,11,6,NaN,THE COAST-TO-COAST MURDERS,2026-03-06T09:12:16.944Z,3,"[{'isbn10': '', 'isbn13': '9780316457422'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4481,11,NaN,https://www.amazon.com/dp/0525536299?tag=thene...,NaN,0,Brit Bennett,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,12,9,NaN,THE VANISHING HALF,2026-03-06T05:54:35.877Z,19,"[{'isbn10': '', 'isbn13': '9780525536291'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4482,12,NaN,https://www.amazon.com/dp/0062868934?tag=thene...,NaN,0,Lucy Foley,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,13,0,NaN,THE GUEST LIST,2026-03-06T05:55:14.795Z,18,"[{'isbn10': '', 'isbn13': '9780062868930'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4483,13,NaN,https://www.amazon.com/Where-Crawdads-Sing-Del...,NaN,0,Delia Owens,https://static01.nyt.com/bestsellers/images/97...,495,328,NaN,...,14,0,NaN,WHERE THE CRAWDADS SING,2026-03-06T05:21:23.135Z,108,"[{'isbn10': '', 'isbn13': '9780735219090'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4484,14,NaN,https://www.amazon.com/dp/1501190652?tag=thene...,NaN,0,Kyle Mills,https://static01.nyt.com/bestsellers/images/97...,500,327,NaN,...,15,7,NaN,VINCE FLYNN: TOTAL POWER,2026-03-06T08:56:37.461Z,4,"[{'isbn10': '', 'isbn13': '9781501190674'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4485,0,NaN,https://www.amazon.com/dp/1538728575?tag=thene...,NaN,0,Nicholas Sparks,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,1,0,NaN,THE RETURN,2026-03-06T09:36:07.62Z,1,"[{'isbn10': '', 'isbn13': '9781538728574'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4486,1,NaN,https://www.amazon.com/dp/0593199308?tag=thene...,NaN,0,Jim Butcher,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,2,0,NaN,BATTLE GROUND,2026-03-06T09:04:31.599Z,1,"[{'isbn10': '', 'isbn13': '9780593199329'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4487,2,NaN,https://www.amazon.com/dp/0525954988?tag=thene...,NaN,0,Ken Follett,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,3,3,NaN,THE EVENING AND THE MORNING,2026-03-06T08:57:01.774Z,3,"[{'isbn10': '', 'isbn13': '9780525954989'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4488,3,NaN,https://www.amazon.com/dp/1982167289?tag=thene...,NaN,0,Lana Del Rey,https://static01.nyt.com/bestsellers/images/97...,500,326,NaN,...,4,0,NaN,VIOLET BENT BACKWARDS OVER THE GRASS,2026-03-06T09:04:34.223Z,1,"[{'isbn10': '', 'isbn13': '9781982167288'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4489,4,NaN,https://www.amazon.com/dp/198481835X?tag=thene...,NaN,0,Jodi Picoult,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,5,1,NaN,THE BOOK OF TWO WAYS,2026-03-06T08:58:44.104Z,2,"[{'isbn10': '', 'isbn13': '9781984818355'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4490,5,NaN,https://www.amazon.com/dp/0316457426?tag=thene...,NaN,0,James Patterson and J.D. Barker,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,6,2,NaN,THE COAST-TO-COAST MURDERS,2026-03-06T09:12:16.944Z,2,"[{'isbn10': '', 'isbn13': '9780316457422'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4491,6,NaN,https://www.amazon.com/dp/1501190652?tag=thene...,NaN,0,Kyle Mills,https://static01.nyt.com/bestsellers/images/97...,500,327,NaN,...,7,5,NaN,VINCE FLYNN: TOTAL POWER,2026-03-06T09:09:07.476Z,3,"[{'isbn10': '', 'isbn13': '9781501190650'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4492,7,NaN,https://www.amazon.com/dp/1501160834?tag=thene...,NaN,0,Fredrik Backman,https://static01.nyt.com/bestsellers/images/97...,500,332,NaN,...,8,7,NaN,ANXIOUS PEOPLE,2026-03-06T09:36:14.162Z,4,"[{'isbn10': '', 'isbn13': '9781501160837'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4493,8,NaN,https://www.amazon.com/dp/0525536299?tag=thene...,NaN,0,Brit Bennett,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,9,6,NaN,THE VANISHING HALF,2026-03-06T05:54:35.877Z,18,"[{'isbn10': '', 'isbn13': '9780525536291'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4494,9,NaN,https://www.amazon.com/dp/0593128486?tag=thene...,NaN,0,Naomi Novik,https://static01.nyt.com/bestsellers/images/97...,500,333,NaN,...,10,0,NaN,A DEADLY EDUCATION,2026-03-06T09:04:49.547Z,1,"[{'isbn10': '', 'isbn13': '9780593128497'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4495,10,NaN,https://www.amazon.com/dp/0062956388?tag=thene...,NaN,0,Lynsay Sands,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,11,0,NaN,IMMORTAL ANGEL,2026-03-06T09:04:51.486Z,1,"[{'isbn10': '', 'isbn13': '9780062956279'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4496,11,NaN,https://www.amazon.com/dp/1496729129?tag=thene...,NaN,0,Joanne Fluke,https://static01.nyt.com/bestsellers/images/97...,500,354,NaN,...,12,0,NaN,CHRISTMAS CUPCAKE MURDER,2026-03-06T09:04:52.682Z,1,"[{'isbn10': '', 'isbn13': '9781496729149'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4497,12,NaN,https://www.amazon.com/dp/0316498939?tag=thene...,NaN,0,Robert Galbraith,https://static01.nyt.com/bestsellers/images/97...,500,330,NaN,...,13,8,NaN,TROUBLED BLOOD,2026-03-06T08:56:38.657Z,3,"[{'isbn10': '', 'isbn13': '9780316498968'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4498,13,NaN,https://www.amazon.com/dp/150118881X?tag=thene...,NaN,0,Ruth Ware,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,14,10,NaN,ONE BY ONE,2026-03-06T09:09:02.774Z,4,"[{'isbn10': '', 'isbn13': '9781501188817'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03
4499,14,NaN,https://www.amazon.com/dp/0525559477?tag=thene...,NaN,0,Matt Haig,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,15,0,NaN,THE MIDNIGHT LIBRARY,2026-03-06T03:15:23.815Z,1,"[{'isbn10': '', 'isbn13': '9780525559474'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-18,2020-10-03

So I need to remove the last 15 rows of the first df

In [10]:
# Number of rows to drop
n = 15

# Dropping last n rows using drop
data_from_2020.drop(data_from_2020.tail(n).index,
        inplace = True)

In [11]:
# checking it worked
data_from_2020.tail(20)

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
4465,10,NaN,https://www.amazon.com/dp/0062667637?tag=thene...,NaN,0,Rumaan Alam,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,11,4,NaN,LEAVE THE WORLD BEHIND,2026-03-06T09:08:31.079Z,2,"[{'isbn10': '', 'isbn13': '9780062667632'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-11-01,2020-10-17
4466,11,NaN,https://www.amazon.com/dp/0525536299?tag=thene...,NaN,0,Brit Bennett,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,12,12,NaN,THE VANISHING HALF,2026-03-06T05:54:35.877Z,20,"[{'isbn10': '', 'isbn13': '9780525536291'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-11-01,2020-10-17
4467,12,NaN,https://www.amazon.com/dp/1501160834?tag=thene...,NaN,0,Fredrik Backman,https://static01.nyt.com/bestsellers/images/97...,500,332,NaN,...,13,8,NaN,ANXIOUS PEOPLE,2026-03-06T09:36:14.162Z,6,"[{'isbn10': '', 'isbn13': '9781501160837'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-11-01,2020-10-17
4468,13,NaN,https://www.amazon.com/dp/0316457426?tag=thene...,NaN,0,James Patterson and J.D. Barker,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,14,11,NaN,THE COAST-TO-COAST MURDERS,2026-03-06T09:12:16.944Z,4,"[{'isbn10': '', 'isbn13': '9780316457422'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-11-01,2020-10-17
4469,14,NaN,https://www.amazon.com/Where-Crawdads-Sing-Del...,NaN,0,Delia Owens,https://static01.nyt.com/bestsellers/images/97...,495,328,NaN,...,15,14,NaN,WHERE THE CRAWDADS SING,2026-03-06T05:21:23.135Z,109,"[{'isbn10': '', 'isbn13': '9780735219090'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-11-01,2020-10-17
4470,0,NaN,https://www.amazon.com/dp/0316435589?tag=thene...,NaN,0,Elin Hilderbrand,https://static01.nyt.com/bestsellers/images/97...,500,322,NaN,...,1,0,NaN,TROUBLES IN PARADISE,2026-03-06T09:08:24.011Z,1,"[{'isbn10': '', 'isbn13': '9780316435611'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4471,1,NaN,https://www.amazon.com/dp/073522465X?tag=thene...,NaN,0,Tana French,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,2,0,NaN,THE SEARCHER,2026-03-06T09:08:27.574Z,1,"[{'isbn10': '', 'isbn13': '9780735224667'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4472,2,NaN,https://www.amazon.com/dp/1538728575?tag=thene...,NaN,0,Nicholas Sparks,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,3,1,NaN,THE RETURN,2026-03-06T09:36:07.62Z,2,"[{'isbn10': '', 'isbn13': '9781538728574'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4473,3,NaN,https://www.amazon.com/dp/0062667637?tag=thene...,NaN,0,Rumaan Alam,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,4,0,NaN,LEAVE THE WORLD BEHIND,2026-03-06T09:08:31.079Z,1,"[{'isbn10': '', 'isbn13': '9780062667632'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4474,4,NaN,https://www.amazon.com/dp/0765387565?tag=thene...,NaN,0,V.E. Schwab,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,5,0,NaN,THE INVISIBLE LIFE OF ADDIE LARUE,2026-03-06T05:54:38.37Z,1,"[{'isbn10': '', 'isbn13': '9780765387561'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4475,5,NaN,https://www.amazon.com/dp/0525954988?tag=thene...,NaN,0,Ken Follett,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,6,3,NaN,THE EVENING AND THE MORNING,2026-03-06T08:57:01.774Z,4,"[{'isbn10': '', 'isbn13': '9780525954989'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4476,6,NaN,https://www.amazon.com/dp/1982108843?tag=thene...,NaN,0,Alice Hoffman,https://static01.nyt.com/bestsellers/images/97...,500,336,NaN,...,7,0,NaN,MAGIC LESSONS,2026-03-06T09:08:33.483Z,1,"[{'isbn10': '', 'isbn13': '9781982108847'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4477,7,NaN,https://www.amazon.com/dp/1501160834?tag=thene...,NaN,0,Fredrik Backman,https://static01.nyt.com/bestsellers/images/97...,500,332,NaN,...,8,8,NaN,ANXIOUS PEOPLE,2026-03-06T09:36:14.162Z,5,"[{'isbn10': '', 'isbn13': '9781501160837'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4478,8,NaN,https://www.amazon.com/dp/198481835X?tag=thene...,NaN,0,Jodi Picoult,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,9,5,NaN,THE BOOK OF TWO WAYS,2026-03-06T08:58:44.104Z,3,"[{'isbn10': '', 'isbn13': '9781984818355'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4479,9,NaN,https://www.amazon.com/dp/1538761467?tag=thene...,NaN,0,David Baldacci,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,10,0,NaN,WALK THE WIRE,2026-03-06T09:08:37.499Z,10,"[{'isbn10': '', 'isbn13': '9781538761472'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4480,10,NaN,https://www.amazon.com/dp/0316457426?tag=thene...,NaN,0,James Patterson and J.D. Barker,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,11,6,NaN,THE COAST-TO-COAST MURDERS,2026-03-06T09:12:16.944Z,3,"[{'isbn10': '', 'isbn13': '9780316457422'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4481,11,NaN,https://www.amazon.com/dp/0525536299?tag=thene...,NaN,0,Brit Bennett,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,12,9,NaN,THE VANISHING HALF,2026-03-06T05:54:35.877Z,19,"[{'isbn10': '', 'isbn13': '9780525536291'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4482,12,NaN,https://www.amazon.com/dp/0062868934?tag=thene...,NaN,0,Lucy Foley,https://static01.nyt.com/bestsellers/images/97...,500,329,NaN,...,13,0,NaN,THE GUEST LIST,2026-03-06T05:55:14.795Z,18,"[{'isbn10': '', 'isbn13': '9780062868930'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4483,13,NaN,https://www.amazon.com/Where-Crawdads-Sing-Del...,NaN,0,Delia Owens,https://static01.nyt.com/bestsellers/images/97...,495,328,NaN,...,14,0,NaN,WHERE THE CRAWDADS SING,2026-03-06T05:21:23.135Z,108,"[{'isbn10': '', 'isbn13': '9780735219090'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10
4484,14,NaN,https://www.amazon.com/dp/1501190652?tag=thene...,NaN,0,Kyle Mills,https://static01.nyt.com/bestsellers/images/97...,500,327,NaN,...,15,7,NaN,VINCE FLYNN: TOTAL POWER,2026-03-06T08:56:37.461Z,4,"[{'isbn10': '', 'isbn13': '9781501190674'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2020-10-25,2020-10-10

## Merging the datasets

In [12]:
master_list = pd.concat([data_from_2020, data_from_2012])

In [13]:
master_list.head()

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
0,0,NaN,https://www.amazon.com/dp/1668236516?tag=thene...,NaN,0,Allen Levi,https://static01.nyt.com/bestsellers/images/97...,0,0,NaN,...,1,1,NaN,THEO OF GOLDEN,2026-03-04T23:40:20.88Z,30,"[{'isbn10': '', 'isbn13': '9781668236512'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
1,1,NaN,https://www.amazon.com/dp/059380421X?tag=thene...,NaN,0,Caro Claire Burke,https://static01.nyt.com/bestsellers/images/97...,400,312,NaN,...,2,2,NaN,YESTERYEAR,2026-04-16T20:39:40.59Z,12,"[{'isbn10': '', 'isbn13': '9780593804216'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
2,2,NaN,https://www.amazon.com/dp/0063511630?tag=thene...,NaN,0,Ann Patchett,https://static01.nyt.com/bestsellers/images/97...,400,312,NaN,...,3,3,NaN,WHISTLER,2026-06-10T21:51:30.058Z,4,"[{'isbn10': '', 'isbn13': '9780063511637'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
3,3,NaN,https://www.amazon.com/dp/1954118813?tag=thene...,NaN,0,Kathryn Stockett,https://static01.nyt.com/bestsellers/images/97...,400,312,NaN,...,4,7,NaN,THE CALAMITY CLUB,2026-05-13T21:30:50.865Z,8,"[{'isbn10': '', 'isbn13': '9781954118812'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27
4,4,NaN,https://www.amazon.com/dp/0593135202?tag=thene...,NaN,0,Andy Weir,https://static01.nyt.com/bestsellers/images/97...,400,312,NaN,...,5,4,NaN,PROJECT HAIL MARY,2026-05-20T22:02:25.385Z,55,"[{'isbn10': '', 'isbn13': '9780593135228'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",2026-07-12,2026-06-27

In [14]:
master_list.tail()

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,rank,rank_last_week,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,published_date,bestsellers_date
9305,30,NaN,http://www.amazon.com/Summer-Garden-Chesapeake...,NaN,0,Sherryl Woods,https://static01.nyt.com/bestsellers/images/97...,440,330,NaN,...,31,0,NaN,THE SUMMER GARDEN,2026-03-07T17:21:29.825Z,0,"[{'isbn10': '', 'isbn13': '9781459220300'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
9306,31,NaN,http://www.amazon.com/The-Paris-Wife-A-Novel-e...,NaN,0,Paula McLain,https://static01.nyt.com/bestsellers/images/97...,400,268,https://www.nytimes.com/2011/02/28/books/28boo...,...,32,0,https://www.nytimes.com/2011/03/20/books/revie...,THE PARIS WIFE,2026-03-07T17:21:32.481Z,0,"[{'isbn10': '', 'isbn13': '9780345521323'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
9307,32,NaN,http://www.amazon.com/Death-Comes-Pemberley-Vi...,NaN,0,P. D. James,https://static01.nyt.com/bestsellers/images/97...,184,128,https://www.nytimes.com/2011/12/27/books/death...,...,33,0,https://www.nytimes.com/2011/12/18/books/revie...,DEATH COMES TO PEMBERLEY,2026-03-08T03:51:26.657Z,0,"[{'isbn10': '', 'isbn13': '9780307959850'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
9308,33,NaN,http://www.amazon.com/44-Charles-Street-A-Nove...,NaN,0,Danielle Steel,https://static01.nyt.com/bestsellers/images/97...,400,261,NaN,...,34,0,NaN,44 CHARLES STREET,2026-03-07T16:59:00.951Z,0,"[{'isbn10': '', 'isbn13': '9780440245179'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25
9309,34,NaN,http://www.amazon.com/Clash-Kings-Song-Fire-Bo...,NaN,0,George R.R. Martin,https://static01.nyt.com/bestsellers/images/97...,280,170,NaN,...,35,0,NaN,A CLASH OF KINGS,2026-03-07T17:15:32.446Z,0,"[{'isbn10': '', 'isbn13': '9780553897852'}]","[{'name': 'Amazon', 'url': 'http://www.amazon....",2012-03-11,2012-02-25

In [15]:
master_list["description"]

0       A man travels to a small Southern town, where ...
1       Natalie Heller Mills, a privileged tradwife so...
2       Decades after their time together, a woman rec...
3       As things get tougher during the Depression, s...
4       Ryland Grace awakes from a long sleep alone an...
                              ...
9305    Falling for Moira was the highlight of Luke’s ...
9306    Hadley Richardson comes into her own as Ernest...
9307    Six years after Elizabeth and Darcy marry, the...
9308    An art gallery owner takes in boarders in her ...
9309    The second book in the Song of Ice and Fire se...
Name: description, Length: 13795, dtype: str

In [16]:
master_list.info()

<class 'pandas.DataFrame'>
Index: 13795 entries, 0 to 9309
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            13795 non-null  int64
 1   age_group             0 non-null      float64
 2   amazon_product_url    13792 non-null  str
 3   article_chapter_link  0 non-null      float64
 4   asterisk              13795 non-null  int64
 5   author                13792 non-null  str
 6   book_image            13763 non-null  str
 7   book_image_height     13795 non-null  int64
 8   book_image_width      13795 non-null  int64
 9   book_review_link      1637 non-null   str
 10  book_uri              13795 non-null  str
 11  contributor           13792 non-null  str
 12  contributor_note      19 non-null     str
 13  created_date          13795 non-null  str
 14  dagger                13795 non-null  int64
 15  description           13673 non-null  str
 16  first_chapter_link    11 non-null     object
 17  price                 13795 non-null  float64
 18  primary_isbn10        0 non-null      float64
 19  primary_isbn13        13795 non-null  object
 20  publisher             13792 non-null  str
 21  rank                  13795 non-null  int64
 22  rank_last_week        13795 non-null  int64
 23  sunday_review_link    1027 non-null   str
 24  title                 13795 non-null  str
 25  updated_date          13795 non-null  str
 26  weeks_on_list         13795 non-null  int64
 27  isbns                 13795 non-null  str
 28  buy_links             13795 non-null  str
 29  published_date        13795 non-null  str
 30  bestsellers_date      13795 non-null  str
dtypes: float64(4), int64(8), object(2), str(17)
memory usage: 3.4+ MB

In [17]:
# Setting the correct index
master_list.index = range(13795)

In [18]:
# Converting dates to datetime
master_list["published_date_as_date"] = pd.to_datetime(master_list["published_date"])
master_list["bestsellers_date_as_date"] = pd.to_datetime(master_list["bestsellers_date"])

In [19]:
master_list.to_csv("raw_data/raw_data_merged.csv")

## Subsetting data for the last decade

In [20]:
df = master_list[master_list.bestsellers_date_as_date > "2016-01-01"]

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 8468 entries, 0 to 8494
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                8468 non-null   int64
 1   age_group                 0 non-null      float64
 2   amazon_product_url        8468 non-null   str
 3   article_chapter_link      0 non-null      float64
 4   asterisk                  8468 non-null   int64
 5   author                    8468 non-null   str
 6   book_image                8468 non-null   str
 7   book_image_height         8468 non-null   int64
 8   book_image_width          8468 non-null   int64
 9   book_review_link          862 non-null    str
 10  book_uri                  8468 non-null   str
 11  contributor               8468 non-null   str
 12  contributor_note          12 non-null     str
 13  created_date              8468 non-null   str
 14  dagger                    8468 non-null   int64
 15  description               8468 non-null   str
 16  first_chapter_link        1 non-null      object
 17  price                     8468 non-null   float64
 18  primary_isbn10            0 non-null      float64
 19  primary_isbn13            8468 non-null   object
 20  publisher                 8468 non-null   str
 21  rank                      8468 non-null   int64
 22  rank_last_week            8468 non-null   int64
 23  sunday_review_link        232 non-null    str
 24  title                     8468 non-null   str
 25  updated_date              8468 non-null   str
 26  weeks_on_list             8468 non-null   int64
 27  isbns                     8468 non-null   str
 28  buy_links                 8468 non-null   str
 29  published_date            8468 non-null   str
 30  bestsellers_date          8468 non-null   str
 31  published_date_as_date    8468 non-null   datetime64[us]
 32  bestsellers_date_as_date  8468 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(4), int64(8), object(2), str(17)
memory usage: 2.2+ MB

In [39]:
# removign any that don't have a description 
df.dropna(subset=["description"], inplace=True)

In [51]:
df.to_csv("data_for_analysis/bestsellers_decade_data.csv")

In [46]:
df.info()

<class 'pandas.DataFrame'>
Index: 8468 entries, 0 to 8494
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                8468 non-null   int64
 1   age_group                 0 non-null      float64
 2   amazon_product_url        8468 non-null   str
 3   article_chapter_link      0 non-null      float64
 4   asterisk                  8468 non-null   int64
 5   author                    8468 non-null   str
 6   book_image                8468 non-null   str
 7   book_image_height         8468 non-null   int64
 8   book_image_width          8468 non-null   int64
 9   book_review_link          862 non-null    str
 10  book_uri                  8468 non-null   str
 11  contributor               8468 non-null   str
 12  contributor_note          12 non-null     str
 13  created_date              8468 non-null   str
 14  dagger                    8468 non-null   int64
 15  description               8468 non-null   str
 16  first_chapter_link        1 non-null      object
 17  price                     8468 non-null   float64
 18  primary_isbn10            0 non-null      float64
 19  primary_isbn13            8468 non-null   object
 20  publisher                 8468 non-null   str
 21  rank                      8468 non-null   int64
 22  rank_last_week            8468 non-null   int64
 23  sunday_review_link        232 non-null    str
 24  title                     8468 non-null   str
 25  updated_date              8468 non-null   str
 26  weeks_on_list             8468 non-null   int64
 27  isbns                     8468 non-null   str
 28  buy_links                 8468 non-null   str
 29  published_date            8468 non-null   str
 30  bestsellers_date          8468 non-null   str
 31  published_date_as_date    8468 non-null   datetime64[us]
 32  bestsellers_date_as_date  8468 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(4), int64(8), object(2), str(17)
memory usage: 2.2+ MB

## Creating a subset of unique values for the AI to analyse

This will keep the cost down and make the analysis run faster as the AI will only need to do the classification on a subset of the data

In [47]:
unique_df = df.drop_duplicates(subset="title")

In [48]:
unique_df.shape

(2242, 33)

In [49]:
unique_df.info()

<class 'pandas.DataFrame'>
Index: 2242 entries, 0 to 8494
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                2242 non-null   int64
 1   age_group                 0 non-null      float64
 2   amazon_product_url        2242 non-null   str
 3   article_chapter_link      0 non-null      float64
 4   asterisk                  2242 non-null   int64
 5   author                    2242 non-null   str
 6   book_image                2242 non-null   str
 7   book_image_height         2242 non-null   int64
 8   book_image_width          2242 non-null   int64
 9   book_review_link          117 non-null    str
 10  book_uri                  2242 non-null   str
 11  contributor               2242 non-null   str
 12  contributor_note          6 non-null      str
 13  created_date              2242 non-null   str
 14  dagger                    2242 non-null   int64
 15  description               2242 non-null   str
 16  first_chapter_link        1 non-null      object
 17  price                     2242 non-null   float64
 18  primary_isbn10            0 non-null      float64
 19  primary_isbn13            2242 non-null   object
 20  publisher                 2242 non-null   str
 21  rank                      2242 non-null   int64
 22  rank_last_week            2242 non-null   int64
 23  sunday_review_link        22 non-null     str
 24  title                     2242 non-null   str
 25  updated_date              2242 non-null   str
 26  weeks_on_list             2242 non-null   int64
 27  isbns                     2242 non-null   str
 28  buy_links                 2242 non-null   str
 29  published_date            2242 non-null   str
 30  bestsellers_date          2242 non-null   str
 31  published_date_as_date    2242 non-null   datetime64[us]
 32  bestsellers_date_as_date  2242 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(4), int64(8), object(2), str(17)
memory usage: 595.5+ KB

In [50]:
unique_df.to_csv("data_for_analysis/data_for_ai_classification.csv")